[project]
name = "awc0001beta"
version = "0.1.0"
requires-python = ">=3.13,<3.14"
dependencies = [
    "networkx==3.5",
    "numba==0.61.2",
    "numpy==2.2.6",
    "online-judge-tools>=11.5.1",
    "setuptools>=82.0.0",
]
